version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
  app:
    build: .
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres

